### ISSUE TITLE
Make it easier to pick up loot

### ISSUE THREAD

**Issue by yousernaym** [duriumm/Pixel-Game#30]
Currently you can only pick up loot with your feet. I think we should use a collider that covers the entire player.

**Comment by duriumm** [comment]
I tihnk this sytem should be a little bit more complex in  the future where the items in a radius gets sucked towards the player like a vaccum and when touching feet collider they get looted

**Comment by yousernaym** [comment]
Sounds good!

**Comment by yousernaym** [comment]
Maybe we could use the `InteractionCollider` to trigger the vacuum.
